# A config for the both cb-network controller and agent as follows:
etcd_cluster:
  endpoints: [ "xxx.xxx.xxx.xxx:xxx", "xxx.xxx.xxx.xxx:xxx", "xxx.xxx.xxx.xxx:xxx" ]

# A config for the cb-network AdminWeb as follows:
admin_web:
  host: "localhost"
  port: "9999"

# A config for the cb-network agent as follows:
cb_network:
  cladnet_id: "xxxx"
  host_id: "" # if host_id is "" (empty string), the cb-network agent will use hostname.
  is_encrypted: false  # false is default.

# A config for the grpc as follows:
grpc:
  service_endpoint: "localhost:8089"
  server_port: "8089"
  gateway_port: "8088"
