# A config for an etcd cluster (required for all cb-netwwork components):
etcd_cluster:
  endpoints: [ "xxx.xxx.xxx.xxx:xxx", "xxx.xxx.xxx.xxx:xxx", "xxx.xxx.xxx.xxx:xxx" ]

# A config for the cb-network admin-web as follows:
admin_web:
  host: "localhost"
  port: "8054"

# A config for the cb-network agent as follows:
cb_network:
  cladnet_id: "xxxx"
  host_id: "" # if host_id is "" (empty string), the cb-network agent will use hostname.
  is_encrypted: false  # false is default.

# A config for the grpc as follows:
grpc:
  service_endpoint: "localhost:8053"
  server_port: "8053"
  gateway_port: "8052"

# A config for the demo-client as follows:
service_call_method: "grpc" # i.e., "rest" / "grpc"
