# A config for an etcd cluster (required for all cb-netwwork components):
etcd_cluster:
  endpoints: [ "localhost:2379" ] # e.g., [ "123.123.123.123:2379", "124.124.124.124:2379", ... ]

# A config for the cb-network service and cb-network admin-web as follows:
service:
  endpoint: "localhost:8053" # e.g., "123.123.123.123:8053"
  port: "8053"

# A config for the cb-network admin-web as follows:
admin_web:
  host: "localhost"
  port: "8054"

# A config for the cb-network agent as follows:
cb_network:
  cladnet_id: "xxxx"
  host: # for each host
    name: "" # if name is "" (empty string), the cb-network agent will use hostname.
    network_interface_name: "" # if network_interface_name is "" (empty string), the cb-network agent will use "cbnet0".
    tunneling_port: "" # if network_interface_port is "" (empty string), the cb-network agent will use "8055".
    is_encrypted: false  # false is default.

# A config for the demo-client as follows:
service_call_method: "grpc" # i.e., "rest" / "grpc"
