## This is a Dockerfile for cb-network admin-web

##############################################################
## Stage 1 - Go Build
##############################################################

FROM golang:1.19 AS builder

ENV GO111MODULE=on

COPY . /cb-larva

WORKDIR /cb-larva/poc-cb-net/cmd/admin-web/

# Build the admin-web
# Note - Using cgo write normal Go code that imports a pseudo-package "C". I may not need on cross-compiling.
# Note - You can find possible platforms by 'go tool dist list' for GOOS and GOARCH
# Note - Using the -ldflags parameter can help set variable values at compile time.
# Note - Using the -s and -w linker flags can strip the debugging information.
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-s -w' -o admin-web

#############################################################
## Stage 2 - Application Setup
##############################################################

FROM alpine:latest

WORKDIR /app

RUN mkdir -p config
RUN mkdir -p web

# Copy the execution file
COPY --from=builder /cb-larva/poc-cb-net/cmd/admin-web/admin-web .
# Copy the web files of the admin-web
COPY --from=builder /cb-larva/poc-cb-net/web/ ./web/

# Ports for the cb-network admin-web
EXPOSE 8054

ENTRYPOINT ["./admin-web"]
